jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - script: npm install
        displayName: 'npm install'
      - task: DotNetCoreInstaller@0
        displayName: 'Use .NET Core sdk 2.1.300'
        inputs:
          version: 2.1.300
      - task: RichCodeNavIndexer@0
        inputs:
          serviceConnection: 'rich-code-nav'
          nugetServiceConnection: 'rich-code-nav-nuget'
          languages: typescript
          githubServiceConnection: 'vsls-contrib'
          serviceEndpoint: 'https://prod.richnav.vsengsaas.visualstudio.com'
  - job: macOS
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - script: npm install
        displayName: 'npm install'
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - script: npm install
        displayName: 'npm install'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
