jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - script: npm install
        displayName: 'npm install'
      - script: npm run compile
        displayName: 'npm compile'
      - script: 'node node_modules/vscode/bin/test'
        displayName: 'Run tests'
      - task: DotNetCoreInstaller@0
        displayName: 'Use .NET Core sdk 2.1.300'
        inputs:
          version: 2.1.300
      - task: vsintellinav.vsck-service-endpoint.build-task.upload-cache-build-task@0
        displayName: 'VS IntelliNav Upload'
        inputs:
          vsckEndpoint: 'vscloudkernel-dev'
          nugetpat: 'vscloudkernel-nuget'
          language: typescript
          githubpat: 'vsls-contrib'
          nugetVersion: '0.1.819-alpha-ge556e1972c'
  - job: macOS
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - script: npm install
        displayName: 'npm install'
      - script: npm run compile
        displayName: 'npm compile'
      - script: 'node node_modules/vscode/bin/test'
        displayName: 'Run tests'
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - script: npm install
        displayName: 'npm install'
      - script: npm run compile
        displayName: 'npm compile'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - script: 'node node_modules/vscode/bin/test'
        displayName: 'Run tests'
        env:
          DISPLAY: :10